version: '3.8'

services:
  app:
    build: .
    container_name: dockerBS
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb+srv://bfanvei:Lolitofernandez10@cluster0.3swo1.mongodb.net/vercel_actividad8?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
