name: Crear y subir imagen docker
on: 
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: construir imagen
        run: docker build -t brobolo/ejemplo-actions:latest .
      - name: subir imagen a dockerhub
        run: docker push brobolo/ejemplo-actions:latest